---
- hosts: lab4
  remote_user: root
  gather_facts: no
  vars:
          ipocts: "{{inventory_hostname|ipsplit}}"
  tasks:
          #          - name: Obtain OS family
          - name: Validate esxcli command 
            stat: path=/bin/esxcli
            register: st 
          - name: Update Linux and Solaris hostname
            command: hostname "E2E-{{labstr}}-{{ipocts[2]}}{{ipocts[3]}}"
            when: st.stat.exists == false
          - name: Update Vmware hostname
            command: esxcli system hostname set --host="E2E-{{labstr}}-{{ipocts[2]}}{{ipocts[3]}}"
            when: st.stat.exists == true


#- hosts: windows
#  gather_facts: no
#  remote_user: root
#  tasks:
#          - name: ping
#            win_ping: 
